baseURL = 'https://bikes.emilyhorsman.com/'
languageCode = 'en-us'
title = "emilyâ€™s bike stuff"
theme = 'bike-theme'
timeout = '240s'
enableRobotsTXT = true

[taxonomies]
  series = 'series'
  tags = 'tags'

[params]
  width = 768

[minify]
  minifyOutput = true
